name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: single contains
        env:
          CONTAINS: ${{ contains('#skip', github.event.head_commit.message) }}
        run: echo "$CONTAINS"
      - name: contains
        env:
          CONTAINS: ${{ contains('#skip', join(github.event.commits.*.message, ' ')) }}
        run: echo "$CONTAINS"


  QA-checks:
    runs-on: ubuntu-20.04
    steps:
      - name: "linting + other things"
        run: echo "checks linting and such"

  deploy:
    needs: QA-checks
    name: Deploy app
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: "deploying"
        run: echo "hi this is now deploying :D"

  tag_release:
    needs: [QA-checks, deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
